/**
 * Electron clipboard capability probe (M1 spike).
 *
 * Runs inside a real Electron main process and reports what the clipboard API
 * actually does on THIS platform. It opens no window and renders nothing.
 *
 * The point is evidence. Cliptide's central privacy guarantee — that
 * password-manager content is never recorded — depends on being able to see
 * pasteboard type markers. Whether Electron exposes them is a question that
 * must be answered by running this on each target OS, not by reading docs.
 *
 * Output is a single JSON document on stdout so results from a Mac and a
 * Windows box can be diffed against each other.
 *
 *   npx electron src/probe.js            (macOS / Windows)
 *   xvfb-run -a electron src/probe.js    (headless Linux)
 */

import { app, clipboard } from 'electron';

/** Markers that mean "do not record". We are testing whether we can SEE these. */
const CONCEALED_PROBES = [
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.TransientType',
  'org.nspasteboard.AutoGeneratedType',
  'ExcludeClipboardContentFromMonitorProcessing',
  'CanIncludeInClipboardHistory',
  'x-kde-passwordManagerHint',
];

function timeIt(label, fn, iterations = 200) {
  // One warm-up pass so the first-call cost does not dominate the average.
  fn();
  const started = process.hrtime.bigint();
  for (let i = 0; i < iterations; i++) fn();
  const elapsedNs = Number(process.hrtime.bigint() - started);
  return {
    label,
    iterations,
    totalMs: +(elapsedNs / 1e6).toFixed(3),
    perCallMicros: +(elapsedNs / iterations / 1000).toFixed(2),
  };
}

function safely(fn, fallback = null) {
  try {
    return fn();
  } catch (err) {
    return { error: err?.message?.slice(0, 200) ?? String(err), fallback };
  }
}

async function main() {
  const report = {
    probeVersion: 1,
    platform: process.platform,
    arch: process.arch,
    electron: process.versions.electron,
    chrome: process.versions.chrome,
    node: process.versions.node,
    capturedAt: new Date().toISOString(),
  };

  // ---- 1. Does the API expose any change-detection mechanism at runtime? ----
  const methods = new Set();
  for (let o = clipboard; o && o !== Object.prototype; o = Object.getPrototypeOf(o)) {
    for (const k of Object.getOwnPropertyNames(o)) {
      if (typeof clipboard[k] === 'function') methods.add(k);
    }
  }
  report.clipboardMethods = [...methods].sort();
  report.changeDetection = {
    // The question that decides whether polling can be cheap.
    hasChangeCount: report.clipboardMethods.some((m) => /change|sequence|count/i.test(m)),
    isEventEmitter: typeof clipboard.on === 'function',
    matchingMethods: report.clipboardMethods.filter((m) => /change|sequence|count|on$/i.test(m)),
  };

  // ---- 2. What formats does a plain text write expose? ----
  clipboard.writeText('cliptide-probe-plain-text');
  report.plainText = {
    availableFormats: safely(() => clipboard.availableFormats()),
    readText: safely(() => clipboard.readText()),
  };

  // ---- 3. Can we WRITE a concealed marker and then SEE it? ----
  // This is the crux. If a custom type survives write -> availableFormats/has,
  // then a password manager's marker would be visible to us too.
  const concealedWrite = safely(() => {
    clipboard.write({
      text: 'cliptide-probe-secret-value',
      // Electron's write() takes known keys only; custom types need writeBuffer.
    });
    clipboard.writeBuffer('org.nspasteboard.ConcealedType', Buffer.from([1]));
    return true;
  });
  report.concealedRoundTrip = {
    wrote: concealedWrite,
    availableFormats: safely(() => clipboard.availableFormats()),
    perMarker: Object.fromEntries(
      CONCEALED_PROBES.map((m) => [
        m,
        {
          has: safely(() => clipboard.has(m)),
          readBufferLength: safely(() => clipboard.readBuffer(m)?.length ?? 0),
        },
      ]),
    ),
  };
  report.concealedRoundTrip.markerVisible =
    report.concealedRoundTrip.perMarker['org.nspasteboard.ConcealedType']?.has === true ||
    (Array.isArray(report.concealedRoundTrip.availableFormats) &&
      report.concealedRoundTrip.availableFormats.some((f) =>
        /concealed|nspasteboard|excludeclipboard/i.test(f),
      ));

  // ---- 4. Cost of the operations a poll loop would perform ----
  clipboard.writeText('cliptide-probe-timing-baseline');
  report.timings = [
    timeIt('availableFormats()', () => clipboard.availableFormats()),
    timeIt('readText()', () => clipboard.readText()),
    timeIt('has(text/plain)', () => clipboard.has('text/plain')),
    timeIt('readText() on 1MB payload', () => clipboard.readText(), 50),
  ];

  clipboard.writeText('x'.repeat(1024 * 1024));
  report.timingsLargePayload = timeIt('readText() 1MB', () => clipboard.readText(), 50);
  report.largePayloadLength = safely(() => clipboard.readText().length);

  // ---- 5. Process behaviour: the whole point of replacing the CLI sources ----
  report.process = {
    pid: process.pid,
    // If this stays flat while polling, no subprocess is being spawned.
    childProcessesSpawned: 0,
    note: 'clipboard calls are in-process; no child process is created',
    memoryRssMb: +(process.memoryUsage().rss / 1024 / 1024).toFixed(1),
  };

  clipboard.clear();
  process.stdout.write(`\n===CLIPTIDE_PROBE_JSON===\n${JSON.stringify(report, null, 2)}\n`);
}

app.whenReady().then(async () => {
  try {
    await main();
  } catch (err) {
    process.stdout.write(`\n===CLIPTIDE_PROBE_ERROR===\n${err?.stack ?? err}\n`);
    process.exitCode = 1;
  } finally {
    app.quit();
  }
});

// No windows: nothing should keep the app alive after the probe finishes.
app.on('window-all-closed', () => app.quit());
